# Generated by Django 3.2.3 on 2021-11-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='ott_name',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='public_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='public_pw',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='title',
            field=models.TextField(),
        ),
    ]
